flowchart LR

A[Source Systems]

A --> B[Extract]

B --> C[Landing Zone]

C --> D[Validation]

D --> E[Transformation]

E --> F[Business Rules]

F --> G[Curated Data]

G --> H[Data Warehouse]

H --> I[Power BI]

H --> J[Tableau]
